version: '3.7'

services:
  euro2024-app:
    container_name: euro2024-app
    build:
      context: ./euro2024-app
    volumes:
      - ./euro2024-app:/app
    command: sh -c "python insert_data.py && gunicorn -c gunicorn_config.py app:app"
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      VIRTUAL_HOST: euro2024.huzeyfe.name
      VIRTUAL_PORT: 5001
      LETSENCRYPT_HOST: euro2024.huzeyfe.name
      LETSENCRYPT_EMAIL: huzeyfeborazan@gmail.com
    networks:
      - finspire

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - finspire

volumes:
  mongo_data:

networks:
  finspire:
    name: finspire
    driver: bridge
