version: '3.8'

services:
  euro2024-app:
    container_name: euro2024-app
    build:
      context: ./euro2024-app
    volumes:
      - ./euro2024-app:/app
    command: sh -c "python insert_data.py && gunicorn -c gunicorn_config.py app:app"
    ports:
      - "5001:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
